# Generated by Django 3.1.4 on 2021-01-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210105_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='jcpaper',
            name='hwl_recommend',
            field=models.BooleanField(default=True),
        ),
    ]
