# Generated by Django 3.1.4 on 2021-01-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_jcpaper_hwl_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to='Protocols/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
