# Generated by Django 3.1.4 on 2021-01-13 07:16

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to=posts.models.make_file_path),
        ),
    ]
