# Generated by Django 3.1.4 on 2020-12-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Primer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sequence', models.CharField(max_length=500)),
                ('modification', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=200)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('volumn', models.CharField(blank=True, max_length=50)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
