# Generated by Django 3.1.4 on 2020-12-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPrimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='primer',
            name='purpose',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
