# Generated by Django 3.1.4 on 2020-12-23 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0003_auto_20201223_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer',
            name='who_ordered',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
