# Generated by Django 3.1.4 on 2021-01-06 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primer', '0004_primer_who_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TPM', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sequence', models.CharField(max_length=20000)),
            ],
        ),
        migrations.AddField(
            model_name='primer',
            name='can_pcr',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='primer',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='primer',
            name='edit_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='primer',
            name='edit_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='edit_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
