# Generated by Django 3.1.4 on 2021-01-08 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0005_auto_20210106_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='primer.project'),
        ),
    ]
