# Generated by Django 3.1.4 on 2021-01-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0007_auto_20210108_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer',
            name='length',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
