# Generated by Django 3.1.4 on 2021-01-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0009_auto_20210108_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primer',
            name='position',
            field=models.IntegerField(default=-1),
        ),
    ]
