# Generated by Django 3.1.4 on 2021-01-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0010_auto_20210108_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primer',
            name='length',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
