# Generated by Django 3.1.4 on 2021-01-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0012_primer_modification_5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primer',
            name='modification',
        ),
        migrations.AddField(
            model_name='primer',
            name='modification_3',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='primer',
            name='modification_internal',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
