# Generated by Django 3.1.4 on 2021-01-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0013_auto_20210114_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primer',
            name='modification_5',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
