# Generated by Django 3.1.4 on 2021-01-14 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0014_auto_20210114_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)])),
                ('modification', models.CharField(default='none', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='primer',
            name='M',
            field=models.ManyToManyField(to='primer.Internal'),
        ),
    ]
