# Generated by Django 3.1.4 on 2021-01-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0015_auto_20210114_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primer',
            name='M',
        ),
        migrations.DeleteModel(
            name='Internal',
        ),
    ]
