# Generated by Django 3.1.4 on 2021-01-15 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0017_auto_20210114_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer',
            name='bottle_name',
            field=models.CharField(default='same with name', max_length=100),
        ),
        migrations.AlterField(
            model_name='primer',
            name='length',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
