# Generated by Django 3.1.4 on 2021-01-15 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0019_primer_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primer',
            name='place',
        ),
    ]
