# Generated by Django 3.1.4 on 2021-01-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0020_remove_primer_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer',
            name='place',
            field=models.CharField(default='Project box', max_length=50),
        ),
    ]
