# Generated by Django 3.1.4 on 2021-01-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0021_primer_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primer',
            name='place',
            field=models.CharField(blank=True, default='Project box', max_length=50),
        ),
    ]
