# Generated by Django 3.1.4 on 2021-02-05 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0022_auto_20210115_1338'),
    ]

    operations = [
        migrations.RenameField('Primer', 'brand', 'vendor'),
    ]
