# Generated by Django 3.1.4 on 2021-01-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='choice',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
